require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");

const Lead = require("../models/Lead");
const Dealership = require("../models/Dealership");
const Inventory = require("../models/Inventory");
const Conversation = require("../models/Conversation");
const Appointment = require("../models/Appointment");

const leads = [
  // ── NEW ENQUIRIES ──
  {
    name: "Sarah Mitchell",
    vehicle: "2025 BYD ATTO 3",
    dealer: "BYD Fairfield VIC",
    score: 12,
    tag: "Contact",
    color: "blue",
    stage: "NEW ENQUIRIES",
    status: "new",
    source: "Carsales",
    phone: "0412 876 543",
    email: "sarah.mitchell@gmail.com",
    stockNum: "5012",
    control: "AI active",
    receivedDaysAgo: 1,
    enquiryDesc: "2025 BYD ATTO 3 with BYD Fairfield VIC",
    enquiryNote: "Is this vehicle still available?",
    price: "$38,990",
    paintColor: "Cosmos Black",
  },
  {
    name: "James Cooper",
    vehicle: "2025 BYD DOLPHIN",
    dealer: "BYD Melbourne City",
    score: 8,
    tag: "Contact",
    color: "blue",
    stage: "NEW ENQUIRIES",
    status: "new",
    source: "SMS Connect",
    phone: "0422 334 556",
    email: "james.cooper@outlook.com",
    stockNum: "5088",
    control: "AI active",
    receivedDaysAgo: 0,
    enquiryDesc: "2025 BYD DOLPHIN with BYD Melbourne City",
    enquiryNote: "What colours are available?",
    price: "$34,890",
    paintColor: "Arctic Blue",
  },
  {
    name: "Priya Sharma",
    vehicle: "2026 BYD SEAL",
    dealer: "BYD Fairfield",
    score: 5,
    tag: "Contact",
    color: "blue",
    stage: "NEW ENQUIRIES",
    status: "new",
    source: "Walk-in",
    phone: "0433 221 998",
    email: "priya.s@yahoo.com",
    stockNum: "6102",
    control: "AI active",
    receivedDaysAgo: 0,
    enquiryDesc: "2026 BYD SEAL with BYD Fairfield",
    enquiryNote: "Looking for a test drive this weekend",
    price: "$49,990",
    paintColor: "Apricity White",
  },
  {
    name: "Tom Williams",
    vehicle: "2025 BYD ATTO 1",
    dealer: "BYD Fairfield VIC",
    score: 15,
    tag: "Contact",
    color: "blue",
    stage: "NEW ENQUIRIES",
    status: "new",
    source: "Facebook",
    phone: "0455 678 123",
    email: "tom.w@gmail.com",
    stockNum: "6944",
    control: "AI active",
    receivedDaysAgo: 2,
    enquiryDesc: "2025 BYD ATTO 1 with BYD Fairfield VIC",
    enquiryNote: "What is the drive-away price?",
    price: "$23,990",
    paintColor: "Pine Lime",
  },

  // ── AI QUALIFYING ──
  {
    name: "SMS Connect Prospect",
    vehicle: "2025 BYD SEAL",
    dealer: "BYD Melbourne City",
    score: 72,
    tag: "Contact",
    color: "blue",
    stage: "AI QUALIFYING",
    status: "qualification",
    source: "SMS Connect",
    phone: "0491 570 201",
    email: "",
    stockNum: "3817",
    control: "AI active",
    receivedDaysAgo: 6,
    enquiryDesc: "2025 BYD SEAL with BYD Melbourne City",
    enquiryNote: "Interested in the SEAL, what finance options?",
    price: "$49,990",
    paintColor: "Cosmos Black",
  },
  {
    name: "Carsalesconnect Prospect",
    vehicle: "2025 BYD SHARK 6",
    dealer: "BYD Fairfield VIC",
    score: 68,
    tag: "Contact",
    color: "blue",
    stage: "AI QUALIFYING",
    status: "qualification",
    source: "Call Connect",
    phone: "0491 570 202",
    email: "",
    stockNum: "4507",
    control: "AI active",
    receivedDaysAgo: 6,
    enquiryDesc: "2025 BYD SHARK 6 with BYD Fairfield VIC",
    enquiryNote: "Want to compare SHARK 6 to HiLux",
    price: "$52,990",
    paintColor: "Apricity White",
  },
  {
    name: "Emily Zhang",
    vehicle: "2025 BYD ATTO 3",
    dealer: "BYD Melbourne City",
    score: 55,
    tag: "Contact",
    color: "amber",
    stage: "AI QUALIFYING",
    status: "qualification",
    source: "Carsales",
    phone: "0413 556 789",
    email: "emily.zhang@proton.me",
    stockNum: "4890",
    control: "AI active",
    receivedDaysAgo: 4,
    enquiryDesc: "2025 BYD ATTO 3 with BYD Melbourne City",
    enquiryNote: "How does the ATTO 3 compare to MG ZS EV?",
    price: "$38,990",
    paintColor: "Arctic Blue",
  },
  {
    name: "Robert Chen",
    vehicle: "2025 BYD SEALION 6",
    dealer: "BYD Fairfield",
    score: 61,
    tag: "Contact",
    color: "blue",
    stage: "AI QUALIFYING",
    status: "qualification",
    source: "SMS Connect",
    phone: "0444 123 876",
    email: "r.chen@work.com.au",
    stockNum: "5200",
    control: "AI active",
    receivedDaysAgo: 3,
    enquiryDesc: "2025 BYD SEALION 6 with BYD Fairfield",
    enquiryNote: "What warranty does BYD offer?",
    price: "$45,990",
    paintColor: "Cosmos Black",
  },
  {
    name: "Atem Tong",
    vehicle: "2025 BYD SHARK 6 Premium",
    dealer: "BYD Fairfield VIC",
    score: 78,
    tag: "Contact",
    color: "blue",
    stage: "AI QUALIFYING",
    status: "qualification",
    source: "Call Connect",
    phone: "0491 570 206",
    email: "atem.t@gmail.com",
    stockNum: "4510",
    control: "AI active",
    receivedDaysAgo: 5,
    enquiryDesc: "2025 BYD SHARK 6 Premium with BYD Fairfield VIC",
    enquiryNote: "Towing capacity and payload?",
    price: "$56,990",
    paintColor: "Apricity White",
  },

  // ── TEST DRIVE BOOKED / COMMITTED ──
  {
    name: "Carsalesconnect Prospect (2)",
    vehicle: "2025 BYD SHARK 6",
    dealer: "BYD Fairfield VIC",
    score: 90,
    tag: "Commitment",
    color: "green",
    stage: "TEST DRIVE BOOKED",
    status: "committed",
    source: "Call Connect",
    phone: "0491 570 203",
    email: "",
    stockNum: "4507",
    control: "AI active",
    receivedDaysAgo: 6,
    enquiryDesc: "2025 BYD SHARK 6 with BYD Fairfield VIC",
    enquiryNote: "Ready for test drive this Saturday",
    price: "$52,990",
    paintColor: "Apricity White",
  },
  {
    name: "David Kennedy",
    vehicle: "2026 BYD SHARK 6 Premium",
    dealer: "BYD Fairfield VIC",
    score: 94,
    tag: "Commitment",
    color: "green",
    stage: "TEST DRIVE BOOKED",
    status: "committed",
    source: "Call Connect",
    phone: "0491 570 204",
    email: "d.kennedy@business.com.au",
    stockNum: "3372",
    control: "Human: Rowland Godeffroy",
    receivedDaysAgo: 6,
    enquiryDesc: "2026 BYD SHARK 6 Premium with BYD Fairfield VIC",
    enquiryNote: "Confirmed test drive + trade-in valuation",
    price: "$59,990",
    paintColor: "Cosmos Black",
  },
  {
    name: "Carsalesconnect Prospect",
    vehicle: "2025 BYD SEALION 8",
    dealer: "BYD Melbourne City",
    score: 58,
    tag: "Contact",
    color: "amber",
    stage: "TEST DRIVE BOOKED",
    status: "committed",
    source: "Carsales",
    phone: "0491 570 205",
    email: "",
    stockNum: "3455",
    control: "AI active",
    receivedDaysAgo: 7,
    enquiryDesc: "2025 BYD SEALION 8 with BYD Melbourne City",
    enquiryNote: "7-seater family SUV interest",
    price: "$67,990",
    paintColor: "Arctic Blue",
  },
  {
    name: "Maria Gonzales",
    vehicle: "2025 BYD DOLPHIN",
    dealer: "BYD Fairfield VIC",
    score: 85,
    tag: "Commitment",
    color: "green",
    stage: "TEST DRIVE BOOKED",
    status: "committed",
    source: "SMS Connect",
    phone: "0477 890 123",
    email: "maria.g@icloud.com",
    stockNum: "5095",
    control: "AI active",
    receivedDaysAgo: 3,
    enquiryDesc: "2025 BYD DOLPHIN with BYD Fairfield VIC",
    enquiryNote: "Booked for Saturday 10am test drive",
    price: "$34,890",
    paintColor: "Apricity White",
  },

  // ── SOLD ──
  {
    name: "Andrew Patel",
    vehicle: "2025 BYD ATTO 3",
    dealer: "BYD Melbourne City",
    score: 100,
    tag: "Commitment",
    color: "green",
    stage: "DELIVERED",
    status: "sold",
    source: "Carsales",
    phone: "0498 765 432",
    email: "a.patel@gmail.com",
    stockNum: "4200",
    control: "Human: Greg Dennis",
    receivedDaysAgo: 14,
    enquiryDesc: "2025 BYD ATTO 3 with BYD Melbourne City",
    enquiryNote: "Purchased and delivered",
    price: "$41,990",
    paintColor: "Cosmos Black",
  },

  // ── LOST ──
  {
    name: "Lisa Thompson",
    vehicle: "2025 BYD SEAL",
    dealer: "BYD Fairfield",
    score: 30,
    tag: "Contact",
    color: "red",
    stage: "LOST",
    status: "lost",
    source: "Facebook",
    phone: "0466 111 222",
    email: "lisa.t@hotmail.com",
    stockNum: "3900",
    control: "AI active",
    receivedDaysAgo: 21,
    enquiryDesc: "2025 BYD SEAL with BYD Fairfield",
    enquiryNote: "Went with a Tesla Model 3 instead",
    price: "$49,990",
    paintColor: "Arctic Blue",
  },

  // ── OPTED OUT ──
  {
    name: "Michael Brown",
    vehicle: "2025 BYD ATTO 1",
    dealer: "BYD Fairfield VIC",
    score: 0,
    tag: "Opted Out",
    color: "red",
    stage: "OPTED OUT",
    status: "opted out",
    source: "SMS Connect",
    phone: "0433 999 888",
    email: "",
    stockNum: "6950",
    control: "AI active",
    receivedDaysAgo: 10,
    enquiryDesc: "2025 BYD ATTO 1 with BYD Fairfield VIC",
    enquiryNote: "Replied STOP",
    price: "$23,990",
    paintColor: "Apricity White",
  },
];

const dealerships = [
  {
    name: "BYD Fairfield",
    legalEntity: "BYD Fairfield (EAutos Group F)",
    address: "72-74 Grand Avenue, Camellia",
    suburb: "Fairfield",
    state: "NSW",
    phone: "(02) 9724 5088",
    email: "sales@bydfairfield.com.au",
    timezone: "Australia/Sydney",
    smsSenderId: "BYDFairfield",
    autogateId: "AG-FAIRFIELD-001",
    autogateUsername: "greg.dennis@bydfairfield.com",
    autogatePassword: "",
    weekdayHoursStart: "09:00",
    weekdayHoursEnd: "20:00",
    saturdayHoursStart: "09:00",
    saturdayHoursEnd: "17:00",
  },
  {
    name: "BYD Fairfield VIC",
    legalEntity: "BYD Fairfield VIC (EAutos Group V)",
    address: "96 Grange Road, Fairfield",
    suburb: "Fairfield",
    state: "VIC",
    phone: "(03) 9000 1234",
    email: "sales@bydfaifieldvic.com.au",
    timezone: "Australia/Melbourne",
    smsSenderId: "BYDFldVIC",
    autogateId: "AG-FAIRFIELD-VIC-001",
    autogateUsername: "sales@bydfaifieldvic.com.au",
    autogatePassword: "",
    weekdayHoursStart: "09:00",
    weekdayHoursEnd: "20:00",
    saturdayHoursStart: "09:00",
    saturdayHoursEnd: "17:00",
  },
  {
    name: "BYD Melbourne City",
    legalEntity: "BYD Melbourne City (EAutos Group)",
    address: "435 Williamstown Road, Port Melbourne",
    suburb: "Port Melbourne",
    state: "VIC",
    phone: "(03) 9646 9000",
    email: "sales@bydmelbourne.com.au",
    timezone: "Australia/Melbourne",
    smsSenderId: "BYDMelb",
    autogateId: "AG-MELCITY-001",
    autogateUsername: "greg.dennis@bydmelbcity.com",
    autogatePassword: "",
    weekdayHoursStart: "09:00",
    weekdayHoursEnd: "20:00",
    saturdayHoursStart: "09:00",
    saturdayHoursEnd: "17:00",
  },
];

const stockNums = ["6944","6993","6942","6990","6994","6991","7819","2871","7277","8618","8617","9854"];
const paints = ["Apricity White", "Pine Lime", "Cosmos Black", "Arctic Blue"];
const locations = ["BYD Wollongong","BYD Wagga Wagga","BYD Castle Hill","BYD Homebush","BYD Haberfield","BYD Campbelltown"];
const prices = ["$23,990","$24,490","$24,751","$25,490","$25,781","$27,164","$27,681","$28,490"];

const inventory = Array.from({ length: 12 }, (_, i) => ({
  stock: stockNums[i],
  model: `${i % 3 ? "2026" : "2025"} BYD ATTO 1`,
  paint: paints[i % 4],
  location: locations[i % 6],
  status: i % 4 === 2 ? "In Transit" : "Available",
  price: prices[i % 8],
}));

const conversations = [
  {
    prospectName: "Carsalesconnect Prospect",
    phone: "0491 570 204",
    initials: "CP",
    dealer: "BYD Melbourne City",
    status: "Contact",
    control: "Human: Rowland Godfrey",
    lastMessage: "Confirmed — I'll call at 3:30pm today. I've kept stock linked to your enquiry.",
    msgCount: 7,
    daysAgo: 4,
  },
  {
    prospectName: "Carsalesconnect Prospect",
    phone: "0491 570 203",
    initials: "CP",
    dealer: "BYD Fairfield VIC",
    status: "Contact",
    control: "AI active",
    lastMessage: "Of course — I'll keep the enquiry active and monitor availability.",
    msgCount: 5,
    daysAgo: 5,
  },
  {
    prospectName: "Atem Tong",
    phone: "0491 570 206",
    initials: "AT",
    dealer: "BYD Fairfield VIC",
    status: "Commitment",
    control: "AI active",
    lastMessage: "Confirmed — I'll call at 3:30pm today. I've kept stock linked to your enquiry.",
    msgCount: 9,
    daysAgo: 6,
  },
  {
    prospectName: "David Kennedy",
    phone: "0491 570 204",
    initials: "DK",
    dealer: "BYD Fairfield VIC",
    status: "Commitment",
    control: "AI active",
    lastMessage: "Of course — I'll keep the enquiry active and monitor availability.",
    msgCount: 12,
    daysAgo: 7,
  },
  {
    prospectName: "SMS Connect Prospect",
    phone: "0491 570 201",
    initials: "SP",
    dealer: "BYD Melbourne City",
    status: "Commitment",
    control: "AI active",
    lastMessage: "Confirmed — I'll call at 3:30pm today. I've kept stock linked to your enquiry.",
    msgCount: 6,
    daysAgo: 8,
  },
  {
    prospectName: "Maria Gonzales",
    phone: "0477 890 123",
    initials: "MG",
    dealer: "BYD Fairfield VIC",
    status: "Commitment",
    control: "AI active",
    lastMessage: "Looking forward to the test drive on Saturday!",
    msgCount: 8,
    daysAgo: 3,
  },
];

const appointments = [
  {
    when: "Fri, 28 Aug, 10:30 am",
    prospectName: "Carsalesconnect Prospect",
    phone: "0491 570 204",
    type: "Callback",
    vehicle: "2025 SEALION 8 7 Seat SUV",
    dealership: "BYD Melbourne City",
    bookedBy: "Agent",
    status: "Confirmed",
  },
  {
    when: "Sat, 29 Aug, 06:00 am",
    prospectName: "Carsalesconnect Prospect (2)",
    phone: "0491 570 203",
    type: "Test Drive",
    vehicle: "2025 SHARK 6 Premium Ute Automatic 1.5",
    dealership: "BYD Fairfield VIC",
    bookedBy: "AI",
    status: "Confirmed",
  },
  {
    when: "Sat, 29 Aug, 09:00 am",
    prospectName: "Atem Tong",
    phone: "0491 570 206",
    type: "Test Drive",
    vehicle: "2025 SHARK 6 Premium Ute Automatic 1.5",
    dealership: "BYD Fairfield VIC",
    bookedBy: "AI",
    status: "Confirmed",
  },
  {
    when: "Mon, 31 Aug, 04:30 am",
    prospectName: "David Kennedy",
    phone: "0491 570 204",
    type: "Test Drive",
    vehicle: "2026 BYD SHARK 6 Premium",
    dealership: "BYD Fairfield VIC",
    bookedBy: "AI",
    status: "Confirmed",
  },
  {
    when: "Sat, 29 Aug, 10:00 am",
    prospectName: "Maria Gonzales",
    phone: "0477 890 123",
    type: "Test Drive",
    vehicle: "2025 BYD DOLPHIN",
    dealership: "BYD Fairfield VIC",
    bookedBy: "AI",
    status: "Confirmed",
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing data
    await Promise.all([
      Lead.deleteMany({}),
      Dealership.deleteMany({}),
      Inventory.deleteMany({}),
      Conversation.deleteMany({}),
      Appointment.deleteMany({}),
    ]);
    console.log("🗑️  Cleared existing data");

    // Insert leads first to get their _ids
    const insertedLeads = await Lead.insertMany(leads);

    // Link conversations to inserted leads by phone or name
    const linkedConversations = conversations.map((c) => {
      const match =
        insertedLeads.find((l) => l.phone === c.phone) ||
        insertedLeads.find(
          (l) => l.name.toLowerCase() === c.prospectName.toLowerCase()
        );
      return {
        ...c,
        leadId: match ? match._id : undefined,
      };
    });

    await Promise.all([
      Dealership.insertMany(dealerships),
      Inventory.insertMany(inventory),
      Conversation.insertMany(linkedConversations),
      Appointment.insertMany(appointments),
    ]);

    console.log("🌱 Seed complete:");
    console.log(`   ${leads.length} leads`);
    console.log(`   ${dealerships.length} dealerships`);
    console.log(`   ${inventory.length} inventory items`);
    console.log(`   ${conversations.length} conversations`);
    console.log(`   ${appointments.length} appointments`);

    process.exit(0);
  } catch (err) {
    console.error("❌ Seed failed:", err.message);
    process.exit(1);
  }
}

seed();
